
#CI Automation testing
name: Run automation

on:
  repository_dispatch:
      types: [ run-dev-tests, run-staging-tests ]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code from github
      uses: actions/checkout@v4
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install necessary libraries
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt

    - name: Set environment testing
      run: |
          if [[ "${{github.event.event_type }}" == "run-dev-tests" ]]; then
            echo "BASE_URL=https://opensource-demo.orangehrmlive.com" >> $GITHUB_ENV 
            echo "BASE_API_URL: https://jsonplaceholder.typicode.com" >> $GITHUB_ENV
          elif [[ "${{github.event.event_type}}" == "run-staging-tests" ]]; then
            echo "hello staging"
          else
            echo "BASE_URL=http://mock" >> $GITHUB_ENV
          fi


    - name: Run Automation tests
      run: |
        if [[ "${{ github.event.event_type}}" == "run-dev-tests" ]]; then
            echo "hello dev {{$BASE_URL}}"
          elif [[ "${{github.event.event_type}}" == "run-staging-tests" ]]; then
            echo "hello staging {{$BASE_URL}}"
          else
            echo "mock" 
          fi 

