
#CI Automation testing
name: Automation CI
run-name: ${{ github.ref_name }} | ${{ github.actor }}
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  UI_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: ["functional"]
        browser: ["Chrome", "Edge"]
    env:
      BROWSER: ${{ matrix.browser }}
      HEADLESS: true
      NAME:  ${{ matrix.suite }}_${{ matrix.browser }}

    steps:
    - name: Checkout source code from github
      uses: actions/checkout@v4
    - name: Install python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install necessary libraries
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt

    - name: Create test report folder
      run: mkdir -p report

    - name: Run test
      run: pytest -m -s ${{matrix.suite}} --html=report/report_${{env.NAME}}.html --maxfail=1 --self-contained-html --disable-warnings

    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report-${{env.NAME}}
        path: report/*.html

  API_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: ["tests/apis" ]
    env:
      NAME: apis

    steps:
      - name: Checkout source code from github
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Create test report folder
        run: mkdir -p report

      - name: Run test
        run: pytest -s ${{matrix.suite}} --html=report/report_${{env.NAME}}.html --self-contained-html --disable-warnings

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{env.NAME}}
          path: report/*.html