
#CI Automation testing
name: Automation CI
run-name: ${{ github.ref_name }} | ${{ github.actor }}
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    if:
    strategy:
      fail-fast: false
      matrix:
        include:
          - suite:  tests/ui/functional/login_page
            name: "login_page"
          - suite: tests/apis
            name: "apis"

    steps:
    - name: Checkout source code from github
      uses: actions/checkout@v4
    - name: Install python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install necessary libraries
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt

    - name: Install Chrome library
      uses: browser-actions/setup-chrome@v1

    - name: Create test report folder
      run: mkdir -p report

    - name: Run test
      run: pytest -s ${{matrix.suite}} --html=report/report_${{matrix.name}}.html --maxfail=1 --self-contained-html --disable-warnings

    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report-${{matrix.name}}
        path: report/*.html
          